service: books

provider:
  name: aws
  runtime: python3.11

package:
  exclude:
    - .gitignore
    - .git/**
    - .vscode/**
    - __pycache__/**
    - node_modules/**
    - venv/**
    - package-lock.json
    - package.json

custom:
  serverless-offline:
    httpPort: 8888

functions:
  listBooks:
    handler: src/functions/books/list_books_handler.handler
    events:
      - httpApi:
          path: /books
          method: GET
  
  getBook:
    handler: src/functions/books/get_book_by_id_handler.handler
    events:
      - httpApi:
          path: /books/{bookId}
          method: GET
  
  createBook:
    handler: src/functions/books/create_book_handler.handler
    events:
      - httpApi:
          path: /books
          method: POST
  
  updateBook:
    handler: src/functions/books/update_book_handler.handler
    events:
      - httpApi:
          path: /books/{bookId}
          method: PUT
      - httpApi:
          path: /books/{bookId}
          method: PATCH
  
  deleteBook:
    handler: src/functions/books/delete_book_handler.handler
    events:
      - httpApi:
          path: /books/{bookId}
          method: DELETE

plugins:
  - serverless-python-requirements
  - serverless-offline