service: books

provider:
  name: aws
  runtime: python3.11
  timeout: 900

package:
  exclude:
    - .gitignore
    - .git/**
    - .vscode/**
    - __pycache__/**
    - node_modules/**
    - venv/**
    - package-lock.json
    - package.json

custom:
  serverless-offline:
    httpPort: 8888

functions:
  listBooks:
    handler: functions/books/list_books.handler
    events:
      - httpApi:
          path: /books
          method: get
  
  getBook:
    handler: functions/books/get_book_by_id.handler
    events:
      - httpApi:
          path: /books/{bookId}
          method: get
  
  createBook:
    handler: functions/books/create_book.handler
    events:
      - httpApi:
          path: /books
          method: post

plugins:
  - serverless-python-requirements
  - serverless-offline